[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
evm_version = "cancun"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config